const { contextBridge, ipcRenderer, webUtils, webFrame } = require('electron')

contextBridge.exposeInMainWorld('api', {
  getConfig: () => ipcRenderer.invoke('get-config'),
  setLang: (lang) => ipcRenderer.invoke('set-lang', lang),
  setInbox: (name) => ipcRenderer.invoke('set-inbox', name),
  chooseRoot: () => ipcRenderer.invoke('choose-root'),
  readDir: (p) => ipcRenderer.invoke('read-dir', p),
  readFile: (p) => ipcRenderer.invoke('read-file', p),
  writeFile: (p, content) => ipcRenderer.invoke('write-file', p, content),
  resolveTarget: (input) => ipcRenderer.invoke('resolve-target', input),
  pollFs: (req) => ipcRenderer.invoke('poll-fs', req),
  getWatch: () => ipcRenderer.invoke('get-watch'),
  probeWatch: (dir, browseRoot) => ipcRenderer.invoke('probe-watch', dir, browseRoot),
  setWatch: (dir, on) => ipcRenderer.invoke('set-watch', dir, on),
  markRead: (p) => ipcRenderer.invoke('mark-read', p),
  dropFiles: (paths) => ipcRenderer.invoke('drop-files', paths),
  pasteClipboard: () => ipcRenderer.invoke('paste-clipboard'),
  getDropLog: () => ipcRenderer.invoke('get-drop-log'),
  dragStart: (p) => ipcRenderer.send('drag-start', p),
  editorUndo: () => ipcRenderer.send('editor-undo'),
  editorRedo: () => ipcRenderer.send('editor-redo'),
  openPath: (p) => ipcRenderer.invoke('open-path', p),
  showInFolder: (p) => ipcRenderer.invoke('show-in-folder', p),
  pathForFile: (file) => webUtils.getPathForFile(file),
  setZoom: (factor) => webFrame.setZoomFactor(factor),
})
